name: Download file from GitHub repository
description: Composite action that downloads a given file from a GitHub repository

author: "CDQ AG"
branding:
  icon: 'download'
  color: 'green'

inputs:
  github-token:
    description: GitHub token with read access to the repository, default GitHub token is used if not provided
    default: "${{ github.token }}"

  repository:
    description: Name of the repository. By default, the repository where the action is run
    default: "${{ github.repository }}"

  file:
    description: File to download
    required: true

  destination:
    description: Custom destination path for the downloaded file, defaults (empty string) to the file name
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Get download URL
      id: get_download_url
      shell: bash
      env: 
        FILE_PATH: ${{ inputs.file }}
        REPOSITORY: ${{ inputs.repository }}
        TOKEN: ${{ inputs.github-token }}
      run: |
        metadata_url="https://api.github.com/repos/${REPOSITORY}/contents/${FILE_PATH}"
        echo "::debug::File metadata URL: $metadata_url"

        download_url=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" "$metadata_url")
        
        download_url=$(echo "$download_url" | jq -r '.download_url')
        if [ "$download_url" == "null" ]; then
          echo "::error::Failed to get download URL for file: $FILE_PATH. Got response: $download_url"
          exit 1
        fi

        echo "::debug::File download URL: $download_url"
        echo "download_url=$download_url" >> $GITHUB_OUTPUT

    - name: Download file
      shell: bash
      env: 
        FILE_PATH: ${{ inputs.file }}
        DESTINATION: ${{ inputs.destination }}
        DOWNLOAD_URL: ${{ steps.get_download_url.outputs.download_url }}
      run: |
        if [ -z "$DESTINATION" ]; then
          DESTINATION=$(basename "$FILE_PATH")
        fi

        curl -L "$DOWNLOAD_URL" -o "$DESTINATION"
